name: Push Build

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Gradle Wrapper Validation
      uses: gradle/wrapper-validation-action@v1

    - name: Setup JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: "zulu"
        java-version: "11"

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Execute Gradle build
      run: ./gradlew build

    - name: Run Spotless
      run: ./gradlew spotlessCheck

    - name: Run Unit Tests
      run: ./gradlew test
